-- V4: Create reviews table for text and video reviews
CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reviewer_name VARCHAR(100) NOT NULL,
    reviewer_role VARCHAR(100),
    review_type VARCHAR(10) NOT NULL DEFAULT 'TEXT',
    rating INTEGER,
    review_text VARCHAR(1000),
    youtube_url VARCHAR(500),
    show_on_homepage BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX idx_reviews_homepage ON reviews(show_on_homepage, active);
CREATE INDEX idx_reviews_type ON reviews(review_type);
